### PR TITLE
Add GD32F10x SPL files from GD32F10x_Firmware_Library_V2.2.4

### PR DESCRIPTION
**Pull request by dmlambo**
In preparation for further F103 changes. No changes made to the files yet, these are directly from GD32F10x_Firmware_Library_V2.2.3.rar

### CODE REVIEW

**Comment by maxgerhardt** [comment]
I remember there were some ever-standing bugs in the verbatim SPL, like them defining their own BOOL / FALSE / TRUE type or a bug in the SPI frequency setting code not clearing the previous value. Will have to look at it carefully.

**Comment by dmlambo** [comment]
Yep, I have those changes in my messy branch. I just wanted to get the verbatim files in there so the changes I make to get it working are more obvious.

**Comment by dmlambo** [comment]
To be clear I won't be adding any changes to this pull request... I intend break up my monolith draft PR into smaller more readable chunks to facilitate discussion, and not litter with thousands of lines of added 3rd party code.

**Comment by dmlambo** [comment]
Just kidding, I couldn't find my source for the rar file, so I grabbed the latest from [GigaDevices](https://www.gd32mcu.com/cn/download/7?kw=GD32F1).

**Pull request merged**
