### PR TITLE
FlashStorage & EEPROM libraries

### PR DESCRIPTION
**Pull request by algernon**
This is a work-in-progress version of my attempt at a pair of FlashStorage & EEPROM libraries.

`FlashStorage` is a lower-level library that abstracts away (most of) the burden of storing and retrieving user data from flash. It simply provides a `read()` and a `write()` method, that handle all the pageing, erasing and updating and whatnot behind the scenes, so the end user doesn't have to care about the low level details.

`EEPROM` builds on top of that, and provides an Arduino-esque `EEPROMClass`, with an API similar to the AVR `EEPROM`. It's more limited than that, because only the basic functionality required for Kaleidoscope is implemented at this point (no C+11 iterators or array access at this point).

There are a few things I need to work out still, namely:
- [x] Sane defaults. At the moment, I copied some defaults from `05_USBD_MSC_internal_flash`. Ideally, we'd have those defaults come from `boards.txt`. The major things we need is the size of the storage, where it starts (or where it ends, which is more practical to store in boards.txt in our case), and the page size.
- [x] Make small operations more efficient. At the moment, _all_ reads and writes require a full page read/write, even if we could do with less. In case of Kaleidoscope, we quite often do much smaller reads and writes.

For reads, we can be _much_ more efficient, because we don't need any paging there. We just read N byes of data from an address, and done.

For writes, the most efficient way would be to copy the whole storage to RAM, and only write back on `commit()`. That'd make writes a lot more efficient, at the cost of ram. Another option would be to have a `prepareWrite()` function, that tells the library how much data we'll write, and where, so it'll prep that area in RAM, and write it all back in `commit()`. This, however, would require dynamic memory allocation. There's `fmc_word_reprogram()`, which should - judging by its comments - reprogram a word at an address without erase. We could use that for more efficient small writes, as we won't have to do full page erase + writes. However, any of these require more thought, and I'll postpone efficient writes 'till a follow-up PR instead. Lets get the very basic functionality working in this one first.

Meanwhile, I'm submitting this as a draft PR for comments, and perhaps ideas. The code has _not_ been tested on hardware yet, I've only done compile tests with this iteration. Once I got to the "test on hardware" stage, I'll report back too.

### CODE REVIEW

**Comment by algernon** [comment]
Hm! There's `fmc_word_reprogram()`, which should - judging by its comments - reprogram a word at an address without erase. We could use that for more efficient small writes, as we won't have to do full page erase + writes.

**Comment by algernon** [comment]
According to the GD32F30x user manual: "The flash page size is 2KB for bank0, 4KB for bank1", with bank0 being the first 512kb. If we use both, we'd need to keep track of two page sizes, an additional complexity. For this reason, I'd restrict the libraries for bank0 only, and hard-code 2k as the page size. If and when we need more than 512kb for this kind of storage, we'll figure something out _then_.

**Comment by algernon** [comment]
Okay... maybe 2k is not the right choice, and it does need to be set in `boards.txt`. If we use a chip that supports more than 512kb of flash, we ideally want this storage at the end, meaning we'll be in the 4kb-page bank. If we use a chip with <= 512kb, we'll be in bank0 with 2kb page sizes.

**Comment by maxgerhardt** [comment]
Just some general thoughts on this:

From the GD32F303xx datasheet:

grafik

So for the GD32F303xx series, the higher the total flash amount, the usable size for code stays the same, just additional space for data storage is added. If the library could only handle Bank0 (up to 512kB total flash), everything starting at CG couldn't be taken proper advantage of. The library should be able to quickly discern whether an address is in a 2kB or 4Kb page because it can subtract the address from the 0x800000 start (to get the offset from flash start), if the offset is less or equal to 512*1024 it's in the Bank0 region and thus 2Kb, else 4Kb.

We must also note that the linker scripts need to be adapted for this, so for the e.g. CC device we can reserve some (user-selectable at best) last sectors for data flash, that must then be subtracted from the available flash for code in the linker script. If a dynamic user selection happens via menus, that must also be mirrored to the PlatformIO builder scripts.

**Comment by algernon** [comment]
For a brief moment, I pondered about not caring about pages, and just using `fmc_word_reprogram()`, 'cos we don't need to erase pages then. But we'd still need to page-align writes, so that's out.

> So for the GD32F303xx series, the higher the total flash amount, the usable size for code stays the same, just additional space for data storage is added.

AHA! Thanks, this makes a few things easier.

> The library should be able to quickly discern whether an address is in a 2kB or 4Kb page because it can subtract the address from the 0x800000 start (to get the offset from flash start), if the offset is less or equal to 512*1024 it's in the Bank0 region and thus 2Kb, else 4Kb.

Mhm. I think I found a reasonably nice way to do just that. Thanks!

> We must also note that the linker scripts need to be adapted for this, so for the e.g. CC device we can reserve some (user-selectable at best) last sectors for data flash, that must then be subtracted from the available flash for code in the linker script. 

For now, I don't think we need dynamic user-selection of storage size, just hard-coding a value for each device in boards.txt should suffice, and we push that down to the linker. Makes things simpler in the beginning, and we can always iterate from that at a future date.

**Comment by algernon** [comment]
Another small update: I moved `EEPROMClass` (the EEPROM emulation layer) from the `EEPROM` library to `FlashStorage`, as `FlashAsEEPROM.h`. This way the `EEPROM` library is a few-line header that simply instantiates `EEPROMClass` to the default size.

This allows us to reuse `EEPROMClass` in other libraries, without having an instantiated `EEPROM` object around, and still have everything function in an Arduino-esque way when including `EEPROM.h`.

**Comment by algernon** [comment]
Collapsed into a single commit, and added a short README. Leaving it as draft still, 'cos I've yet to test this on hardware still.

**Comment by maxgerhardt** [comment]
I see you've added ` -DARDUINO_UPLOAD_MAXIMUM_SIZE={upload.maximum_size}` to the Arduino IDE build flags, you can mirror that in the `tools/platformio/platformio-build.py` by expanding the `CPPDEFINES` array (line 214) with the same element: 

```py
    CPPDEFINES=[
        series,
        ("ARDUINO", 10808),
        ("F_CPU", "$BOARD_F_CPU"), # for compatiblity
        "ARDUINO_ARCH_GD32",
        "ARDUINO_%s" % board_id,
        ("BOARD_NAME", '\\"%s\\"' % board_id),
        ("ARDUINO_UPLOAD_MAXIMUM_SIZE", board_config.get("upload.maximum_size"))
    ],
```

**Comment by algernon** [comment]
Had a good night's sleep, and it dawned on me that we do not need to always position the storage at the end of flash, restricting us to one instance of the class. We can _default_ to that, but still allow setting a position, with a template argument. We can have multiple storages this way, with reasonable defaults.

The advantage of not overwriting it (at least under normal circumstances) when flashing new firmware still remains. But the disadvantage of having to augment the linker to reserve space also remains. I still believe that's a fair compromise.

**Comment by algernon** [comment]
Pushed the latest version. As it turns out, we can't use `fmc_word_reprogram` to speed up writes, and using full page read/update/write cycles for small data is prohibitively slow. For this reason, we use a buffer of the size of the full storage: writes update this, read reads from this, and we only write it back to flash when calling `.commit()`. We also fill up the buffer with flash storage contents during `begin()`.

I've tested this on a starter board, and everything seems to work fine, commit speed (at 10k storage) is perfectly fine, too. I still need to update the docs, however.

**Comment by algernon** [comment]
Squashed it all together and force pushed, everything should be up to date now, so I'm marking this as ready for review.

For reference, committing 1k to storage is about 6.8ms, perfectly good speed, considering commits should be reasonably rare.

**Comment by obra** [comment]
Looks good to me. @maxgerhardt - anything in particular you want to check or review before merge?

**Comment by maxgerhardt** [comment]
I was going to code review + test on real HW this weekend more in-depth. Especially taking into account possibly needed changes to the linkerscript to reserve space, possible menu selection on how much space is reserved in the Arduino IDE (and `platformio.ini` option for PlatformIO), how much sense it makes to have the FlashStorageLibrary along with the EEPROM library due to how they interwork in a (hopefully?) compatible way, how efficient the FlashStorageLibrary etc is.

**Comment by algernon** [comment]
Apologies for the late reply!

> how much sense it makes to have the FlashStorageLibrary along with the EEPROM library due to how they interwork in a (hopefully?) compatible way, how efficient the FlashStorageLibrary is, ...

I'd say none, mostly because `EEPROM` creates a storage instance when included. If they were in the same library, that library would either be `FlashStorage` or `EEPROM`. If it's the former, then to use eeprom, one would have to include both headers for Arduino to find `EEPROM`, which isn't what happens on most platforms. If it was in the latter, then one would have to include `EEPROM.h`, thus creating a storage instance implicitly, which is not always the desired behaviour. So having them separate is the most practical solution, in my opinion.

> possibly needed changes to the linkerscript to reserve space, possible menu selection on how much space is reserved in the Arduino IDE (and platformio.ini option for PlatformIO)

Not sure about PIO, but for Arduino, we might not even need a linker script. We can just create menu items that override the maximum upload size, to be the real storage size - reserved, and arduino will error out if that's reached. So we do the reserve a few levels higher than the linker, with a possibly more descriptive error message.

**Comment by maxgerhardt** [comment]
I see. I have to yet look over this, but hopefully I can get it done this weekend.

**Comment by maxgerhardt** [comment]
@algernon Alright I took a look at the stuff:
* I had to correct multiple compiler errors and warnings to get it to compile, predominantly `FlashStorage::write()` with **const** uint8_t*, otherwise due to a `-Werror` it would fail compilation
* Added `EEPROM::commit()` function exposing the underlying `storage_.commit()`. Without that, users of only the  `EEPROM.h` library could never actually "flush" the changes to the actual Flash, only write into the RAM buffer
* Added a erase + write + read example in the EEPROM library

The library works fine on my GD32F303CC. However, I see the following issues:
* The `FlashStorage` class and `EEPROM` class are architecturally weird. In the reference library (https://github.com/cmaglie/FlashStorage/tree/master/src), the `FlashStorage` class's `write()` function **directly** writes to the flash, has no bufferung, and the `EEPROM` class has the logic to only write into a buffer and flush / `.commit()` changes to the flash. The implementation here is exactly reversed: The `FlashStorage`'s `write()` function only writes to a buffer it manages and has a `.commit()` function. Do we want to keep this design or equalize it with the other library? Or keep it for convience, but then always impose the RAM buffer overhead on users ony using the `FlashStorage` class?
* Code like `static constexpr uint32_t bank0_end = fmc_base_address + 512 * 1024 - 1;` probably only works for the GD32F30x series, which is the only series for which this core has full support -- for future series support, we need to keep in mind that this may change. Seems okay for now.

I'm merging as of now since this is working, the rest can be addressed in later PRs or tracked in issues.

**Comment by algernon** [comment]
> @algernon Alright I took a look at the stuff:
> 
> * I had to correct multiple compiler errors and warnings to get it to compile, predominantly `FlashStorage::write()` with **const** uint8_t*, otherwise due to a `-Werror` const type conversion it would fail compilation

Sorry about that, I forgot to enable -Werror, so didn't see those.

> * The `FlashStorage` class and `EEPROM` class are architecturally weird. In the reference library (https://github.com/cmaglie/FlashStorage/tree/master/src), the `FlashStorage` class's `write()` function **directly** writes to the flash, has no bufferung, and the `EEPROM` class has the logic to only write into a buffer and flush / `.commit()` changes to the flash. The implementation here is exactly reversed: The `FlashStorage`'s `write()` function only writes to a buffer it manages and has a `.commit()` function, the EEPROM class inherits all this without having to do its own buffering logic. Do we want to keep this design or equalize it with the other library? Or keep it for convience, but then always impose the RAM buffer overhead on users only using the `FlashStorage` class?

I'd rather keep the current architecture, because it allows users of the `FlashStorage` class to have it be efficient, without having to reimplement the buffering EEPROM does. On the other hand, I do see value in having a raw class without the buffering. So how about a compromise? `FlashStorage` would become a class that has no buffering, does direct writes and reads. We'd build `BufferedFlashStorage` on top of that, that does the buffering, and adjust `EEPROM` to use `BufferedFlashStorage`.

This way we'd satisfy all three scenarios: flash storage without buffering, with buffering, and EEPROM emulation on top of the latter.

> * Code like `static constexpr uint32_t bank0_end = fmc_base
_address + 512 * 1024 - 1;` probably only works for the GD32F30x series, which is the only series for which this core has full support -- for future series support, we need to keep in mind that this may change. Seems okay for now.

Suppose we can add a `TODO` comment above it?

**Comment by maxgerhardt** [comment]
>FlashStorage would become a class that has no buffering, does direct writes and reads. We'd build BufferedFlashStorage on top of that, that does the buffering, and adjust EEPROM to use BufferedFlashStorage.

But wouldn't the EEPROM class then be just a diplication of `BufferedFlashStorage`? Users that want this can directly use the global `EEPROM` object. Otherwise, I'm all of for either having `FlashStorage` do direct read/writes and EEPROM doing buffering, just like the reference EEPROM and FlashStorage libraries, just out of principle. But it works fine now too.

>Suppose we can add a TODO comment above it? 

Yes that would be good

**Comment by algernon** [comment]
> > FlashStorage would become a class that has no buffering, does direct writes and reads. We'd build BufferedFlashStorage on top of that, that does the buffering, and adjust EEPROM to use BufferedFlashStorage.
> 
> But wouldn't the EEPROM class then be just a duplication of `BufferedFlashStorage`? 

The `EEPROMClass` class would wrap `BufferedFlashStorage` in this case. Not a duplication, but a thin wrap, exactly like how `EEPROMClass` in the current state is a thin wrap around `FlashStorage`. The only change to `EEPROMClass` in the proposed scenario would be `s/FlashStorage/BufferedFlashStorage/`.

> Users that want this can directly use the global `EEPROM` object.

The reason I don't like the buffering being in `EEPROMClass` is that would make it harder to have a storage object with buffering that does _not_ use the `EEPROM` APIs, nor the global object (because they want the storage at a different place, or they want multiple storage spaces, etc).

Having a FlashStorage -> BufferedFlashStorage -> EEPROMClass chain allows more flexibility, imo. We'd have direct read/write with `FlashStorage`, the current buffered behaviour with `BufferedFlashStorage`, and an EEPROM API wrapper with `EEPROMClass` (+ the `EEPROM` global object via the EEPROM library). Everyone can pick whichever class fits their goal best. Could even make `EEPROMClass` templateable, so one can create an instance backed by `FlashStorage`, or one backed by `BufferedFlashStorage` (with the global EEPROM object using the latter).

While this is different than the reference implementation, I think the increased flexibility is worth being different.

**Comment by maxgerhardt** [comment]
I see. Indeed, this would a good further improvement then.

**Pull request merged**
